name: Claude Code Review

description: 'Automated code review using Claude AI'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude'
    required: true
  max_turns:
    description: 'Maximum number of turns for Claude interaction'
    required: false
    default: '10'
  timeout_minutes:
    description: 'Timeout for Claude interaction in minutes'
    required: false
    default: '5'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 1

    - name: Run Claude Code
      uses: anthropics/claude-code-action@e26577a930883943cf9d90885cd1e8da510078dd
      with:
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        max_turns: ${{ inputs.max_turns }}
        timeout_minutes: ${{ inputs.timeout_minutes }}


