name: "Claude Code Security Review"
description: "AI-powered security review using Claude with configurable options"

inputs:
  claude-api-key:
    description: "Anthropic Claude API key for security analysis"
    required: true
  custom-security-scan-instructions:
    description: "Path to custom security scan instructions text file"
    required: false
    default: ""
  false-positive-filtering-instructions:
    description: "Path to custom false positive filtering instructions text file"
    required: false
    default: ""
  claudecode-timeout:
    description: "Timeout for ClaudeCode analysis in minutes"
    required: false
    default: "20"
  exclude-directories:
    description: "Comma-separated list of directories to exclude from scanning"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Run Claude Code Security Review
      uses: anthropics/claude-code-security-review@main
      with:
        claude-api-key: ${{ inputs.claude-api-key }}
        comment-pr: true
        exclude-directories: ${{ inputs.exclude-directories }}
        claudecode-timeout: ${{ inputs.claudecode-timeout }}
        false-positive-filtering-instructions: ${{ inputs.false-positive-filtering-instructions }}
        custom-security-scan-instructions: ${{ inputs.custom-security-scan-instructions }}
