name: Claude Code Review

description: 'Automated code review using Claude AI'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude'
    required: true
  max_turns:
    description: 'Maximum number of turns for Claude interaction (max: 10)'
    required: false
    default: '5'
  timeout_minutes:
    description: 'Timeout for Claude interaction in minutes (max: 10)'
    required: false
    default: '5'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 1

    - name: Validate inputs
      shell: bash
      run: |
        if [ "${{ inputs.max_turns }}" -gt 10 ]; then
          echo "Error: max_turns cannot exceed 10"
          exit 1
        fi
        if [ "${{ inputs.timeout_minutes }}" -gt 10 ]; then
          echo "Error: timeout_minutes cannot exceed 10"
          exit 1
        fi
        
    - name: Run Claude Code
      uses: anthropics/claude-code-action@e26577a930883943cf9d90885cd1e8da510078dd
      with:
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        max_turns: ${{ inputs.max_turns }}
        timeout_minutes: ${{ inputs.timeout_minutes }}


